apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 448834494888.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "akshaya123"
            - name: MYSQL_DATABASE
              value: "employees"
      imagePullSecrets:
        - name: ecr-secret
