apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 448834494888.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "akshaya123"
            - name: DATABASE
              value: "employees"
            - name: DBPORT  
              value: "3306"  
      imagePullSecrets:
        - name: ecr-secret
