apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp-container
          image: 448834494888.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "akshaya123"
            - name: DATABASE
              value: "employees"
            - name: DBPORT
              value: "3306"
      imagePullSecrets:
        - name: ecr-secret
